# Generated by Django 4.1.5 on 2023-02-18 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Achateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Produit_name', models.CharField(max_length=10)),
                ('Quantite', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='adminRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Achateur_name', models.CharField(max_length=30)),
                ('Produit_name', models.CharField(max_length=30)),
                ('Fourniseur_name', models.CharField(max_length=30)),
                ('societe', models.CharField(default='my socite', max_length=500)),
                ('Prix', models.PositiveIntegerField()),
                ('Quantite', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('request_by_Achateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Achateur.achateur')),
            ],
        ),
    ]
