# Generated by Django 4.1.5 on 2023-02-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAchat', '0003_alter_adminrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
