# Generated by Django 4.1.5 on 2023-02-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAchat', '0004_alter_adminrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrequest',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
