# Generated by Django 4.1.5 on 2023-03-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAchat', '0005_alter_adminrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrequest',
            name='Achateur_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
